services:
    GaylordP\UserBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        autoconfigure: true
        autowire: true

    GaylordP\UserBundle\EventListener\CreatableListener:
        autowire: true
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'prePersist'

    GaylordP\UserBundle\EventListener\ResponseListener:
        arguments:
            - '@security.helper'
            - '@GaylordP\UserBundle\Mercure\UserCookieGenerator'
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    GaylordP\UserBundle\Form\UserNewPasswordType:
        arguments:
            - '@security.password_encoder'
            - '@translator'
        tags:
            - 'form.type'

    GaylordP\UserBundle\Handler\LogoutSuccessHandler:
        arguments:
            - '@security.helper'
            - '@router.default'
            - '@twig'

    GaylordP\UserBundle\Mercure\UserCookieGenerator:
        arguments:
            - '%env(MERCURE_JWT_KEY)%'
            - '%kernel.environment%'

    GaylordP\UserBundle\Mercure\JwtProvider:
        arguments:
            - '%env(MERCURE_JWT_KEY)%'

    GaylordP\UserBundle\NotificationFormat\NotificationFormat:

    GaylordP\UserBundle\NotificationFormat\UserNotificationFormat:
        tags:
            - 'user.notification_format'

    GaylordP\UserBundle\Provider\UserProvider:
        arguments:
            - '@security.helper'
            - '@GaylordP\UserBundle\Repository\UserFollowRepository'

    GaylordP\UserBundle\Repository\UserFollowRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserBundle\Repository\UserForgotPasswordRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserBundle\Repository\UserRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserBundle\Repository\Filter\DeletedAtFilter:
        arguments:
            - '@doctrine.orm.entity_manager'

    GaylordP\UserBundle\Security\Authentificator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router.default'
            - '@security.csrf.token_manager'
            - '@security.password_encoder'
            - '%form_login_default_target_path%'
            - '@twig'
            - '@translator'

    GaylordP\UserBundle\Validator\UserEmailValidator:
        arguments:
            - '@GaylordP\UserBundle\Repository\UserRepository'
        tags:
            - 'validator.constraint_validator'

    GaylordP\UserBundle\Validator\UserPasswordOldNewSameValidator:
        arguments:
            - '@security.helper'
            - '@security.password_encoder'
        tags:
            - 'validator.constraint_validator'
